kind = "web"
previewPath = "/"
title = "Brandmusic"
version = "1.0.0"
id = "artifacts/brandmusic"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19436

[services.development]
run = "pnpm --filter @workspace/brandmusic run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/brandmusic", "run", "build" ]
publicDir = "artifacts/brandmusic/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19436"
BASE_PATH = "/"
